apiVersion: v2
name: xconf
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: v0.1.3

dependencies:
  - name: micro
    version: 0.1.0
    condition: micro-api.enabled
    alias: micro-api
  - name: service
    version: 0.1.0
    condition: config-srv.enabled
    alias: config-srv
  - name: service
    version: 0.1.0
    condition: admin-api.enabled
    alias: admin-api
  - name: service
    version: 0.1.0
    condition: agent-api.enabled
    alias: agent-api
