kind: Deployment
apiVersion: apps/v1
metadata:
  name: admin-api
  namespace: xconf
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
    spec:
      containers:
        - name: admin-api
          image: 'xuxu123/admin-api:v0.1.3'
          imagePullPolicy: Always
          env:
            - name: MICRO_SERVER_ADDRESS
              value: 0.0.0.0:8080
            - name: MICRO_REGISTRY
              value: "etcd"
            - name: MICRO_REGISTRY_ADDRESS
              value: $MICRO_REGISTRY_ADDRESS
          ports:
            - containerPort: 8080
