kind: Deployment
apiVersion: apps/v1
metadata:
  name: agent-api
  namespace: xconf
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: agent-api
  template:
    metadata:
      labels:
        app: agent-api
    spec:
      containers:
        - name: agent-api
          image: 'xuxu123/agent-api:v0.1.3'
          imagePullPolicy: Always
          env:
            - name: MICRO_SERVER_ADDRESS
              value: 0.0.0.0:8080
            - name: XCONF_CACHE_SIZE
              value: "1048576"
            - name: MICRO_REGISTRY
              value: "etcd"
            - name: MICRO_REGISTRY_ADDRESS
              value: $MICRO_REGISTRY_ADDRESS
          ports:
            - containerPort: 8080
