kind: Deployment
apiVersion: apps/v1
metadata:
  name: micro
  namespace: xconf
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: micro
  template:
    metadata:
      labels:
        app: micro
    spec:
      containers:
        - name: micro
          image: 'xuxu123/micro:v0.1.3'
          imagePullPolicy: Always
          env:
            - name: MICRO_REGISTRY
              value: "etcd"
            - name: MICRO_REGISTRY_ADDRESS
              value: $MICRO_REGISTRY_ADDRESS
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: xconf
  name: micro
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: micro
  type: LoadBalancer
