{{- if .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "xconf.serviceAccountName" . }}
  labels:
{{- include "xconf.labels" . | nindent 4 }}
{{- end -}}
